acseo_sylius_brand_shop_brand_show:
    path: /brand/{code}
    methods: [GET]
    defaults:
        _controller: acseo_sylius_brand.controller.brand:showAction
        _sylius:
            template: "@ACSEOSyliusBrandPlugin/Shop/Brand/show.html.twig"
            repository:
                method: findOneByCode
                arguments:
                    - $code
